exclude: 'build/'

default_language_version:
    python: python3.12

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Latest stable version
    hooks:
    -   id: check-merge-conflict
        args: ['--assume-in-merge']
    -   id: trailing-whitespace
        exclude: '\.py$'  # Exclude Python files as Ruff already handles them
    -   id: check-added-large-files
        args: ['--maxkb=1000']
    -   id: end-of-file-fixer
        exclude: '^(.*\.svg)$'
    -   id: no-commit-to-branch
    -   id: check-yaml
        args: ["--unsafe"]
    -   id: detect-private-key
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
        args: [--fix=lf] # Forces to replace line ending by LF (line feed)
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format

-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
    -   id: shellcheck

-   repo: local
    hooks:
      - id: pkg-gen
        name: Distribution Build
        entry: ./distribution/build.py
        language: python
        pass_filenames: false
        require_serial: true
        always_run: true
        files: ^distribution/.*$
        additional_dependencies:
          - llama-stack==0.2.23

      - id: doc-gen
        name: Distribution Documentation
        entry: ./scripts/gen_distro_docs.py
        language: python
        pass_filenames: false
        require_serial: true
        files: ^distribution/run\.yaml$
        additional_dependencies:
          - pyyaml==6.0.2
